project_id = "okphvwfomnjeltkydsqw"

[functions.send-email]
verify_jwt = true

[functions.generate-monthly-billings]
verify_jwt = false

[functions.billing-due-reminder]
verify_jwt = false

[functions.validate-cnpj]
verify_jwt = false

[functions.contract-expiration-alerts]
verify_jwt = false

[functions.send-urgent-announcement]
verify_jwt = true

[functions.contract-signed-notification]
verify_jwt = false

[functions.retry-notifications]
verify_jwt = false
